### ISSUE TITLE
How to install via cocoapod?

### ISSUE THREAD

**Issue by linhVmodev** [kean/ImageTaskBuilder#1]

**Comment by kean** [comment]
It doesn't have CocoaPods support. The only installation option is Swift Package Manager.

**Comment by linhVmodev** [comment]
@kean 1 more question
Will `.resize(width: 320)` also reduce cache size?

**Comment by kean** [comment]
In-memory cache, yes. On-disk cache, depending on how you configure it. You can opt-in to store only processed images on disk. This is not the default. See Nuke README for more info.

**Comment by linhVmodev** [comment]
Ok, thanks so much.
